spring.application.name=aisearch

spring.datasource.url=jdbc:postgresql://localhost:5432/aisearch
spring.datasource.username=postgres
spring.datasource.password=its4postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=${GEMINI_API_KEY}

gemini.embedding.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-001:embedContent

gemini.chat.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

spring.profiles.include=local