import { useEffect, useState } from 'react';
import { DashboardLayout } from '../layouts/DashboardLayout';
import { SectionHeader } from '../components/SectionHeader';
import { StatusMessage } from '../components/StatusMessage';
import { api, ApiError } from '../services/api';
import type { DocumentRecord, NoteRecord, RagResponse } from '../types/api';
import { readableError } from '../utils/errors';

function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }

export function DashboardPage() {
  const [active, setActive] = useState('overview');
  const [documents, setDocuments] = useState<DocumentRecord[]>([]);
  const [notes, setNotes] = useState<NoteRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState('');
  useEffect(() => { Promise.all([api.documents(), api.notes()]).then(([docs, nextNotes]) => { setDocuments(docs); setNotes(nextNotes); }).catch(error => setLoadError(readableError(error, 'Could not load your workspace.'))).finally(() => setLoading(false)); }, []);
  return <DashboardLayout active={active} onChange={setActive}><div className="content-wrap">{loading ? <div className="loading-state">Loading your workspace...</div> : loadError ? <StatusMessage>{loadError}</StatusMessage> : active === 'documents' ? <DocumentsView documents={documents} onUploaded={document => setDocuments(current => [document, ...current])} /> : active === 'ask' ? <AskView /> : active === 'notes' ? <NotesView notes={notes} onChange={setNotes} /> : <Overview documents={documents} notes={notes} onChange={setActive} />}</div></DashboardLayout>;
}

function Overview({ documents, notes, onChange }: { documents: DocumentRecord[]; notes: NoteRecord[]; onChange: (value: string) => void }) {
  return <><SectionHeader eyebrow="Your workspace" title="Good to see you." description="A focused place for the ideas hiding in your files." /><div className="stat-grid"><button className="stat-card" onClick={() => onChange('documents')}><span className="stat-value">{documents.length}</span><span className="stat-label">Documents indexed <b>→</b></span></button><button className="stat-card" onClick={() => onChange('notes')}><span className="stat-value">{notes.length}</span><span className="stat-label">Notes captured <b>→</b></span></button><button className="stat-card accent" onClick={() => onChange('ask')}><span className="stat-value">Ask</span><span className="stat-label">Search your knowledge <b>→</b></span></button></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><h2>Recent documents</h2><button className="text-button" onClick={() => onChange('documents')}>View all →</button></div>{documents.length ? documents.slice(0, 4).map(document => <DocumentRow key={document.id} document={document} />) : <EmptyState title="No documents yet" text="Upload a PDF or TXT to give Dronzer something to understand." action="Upload a document" onClick={() => onChange('documents')} />}</section><section className="panel dark-panel"><p className="eyebrow">RAG WORKSPACE</p><h2>Ask a better question.</h2><p>Get answers grounded in the documents you have already indexed.</p><button className="button button-light" onClick={() => onChange('ask')}>Open search <span>→</span></button></section></div></>;
}

function DocumentsView({ documents, onUploaded }: { documents: DocumentRecord[]; onUploaded: (document: DocumentRecord) => void }) {
  const [dragging, setDragging] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function upload(file?: File) { if (!file) return; setMessage(''); setError(''); setBusy(true); try { const document = await api.upload(file); onUploaded(document); setMessage(`${document.filename} is now indexed.`); } catch (requestError) { setError(readableError(requestError, 'Upload failed. The document was not saved.')); } finally { setBusy(false); } }
  return <><SectionHeader eyebrow="Knowledge base" title="Documents" description="Add the source material Dronzer will search and cite." action={<button className="button button-dark" onClick={() => document.getElementById('file-input')?.click()} disabled={busy}>{busy ? 'Uploading...' : '+ Upload file'}</button>} /><input id="file-input" className="visually-hidden" type="file" accept=".pdf,.txt,application/pdf,text/plain" onChange={event => upload(event.target.files?.[0])} /><div className={`drop-zone ${dragging ? 'dragging' : ''}`} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); upload(event.dataTransfer.files[0]); }}><span className="upload-glyph">↑</span><strong>{busy ? 'Processing your file...' : 'Drop a document here'}</strong><span>PDF or TXT · up to 10 MB</span><button className="text-button" onClick={() => document.getElementById('file-input')?.click()}>Choose from your device</button></div>{error && <StatusMessage>{error}</StatusMessage>}{message && <StatusMessage tone="success">{message}</StatusMessage>}<section className="panel table-panel"><div className="panel-heading"><h2>Indexed documents <span className="count">{documents.length}</span></h2></div>{documents.length ? documents.map(document => <DocumentRow key={document.id} document={document} />) : <EmptyState title="Your knowledge base is empty" text="Documents you upload will appear here after successful processing." />}</section></>;
}

function AskView() {
  const [question, setQuestion] = useState(''); const [result, setResult] = useState<RagResponse | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function ask() { if (!question.trim()) return; setBusy(true); setError(''); setResult(null); try { setResult(await api.ask(question.trim())); } catch (requestError) { setError(readableError(requestError, 'We could not complete that question.')); } finally { setBusy(false); } }
  return <><SectionHeader eyebrow="Grounded answers" title="Ask Dronzer" description="Ask in plain language. The answer will stay close to your sources." /><section className="ask-panel"><label htmlFor="question">What would you like to know?</label><textarea id="question" rows={4} value={question} onChange={event => setQuestion(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) ask(); }} placeholder="e.g. What are the main decisions in the product brief?" /><div className="ask-footer"><span>Answers are grounded in your indexed documents.</span><button className="button button-dark" onClick={ask} disabled={busy || !question.trim()}>{busy ? 'Thinking...' : 'Ask Dronzer →'}</button></div></section>{error && <StatusMessage>{error}</StatusMessage>}{result && <section className="answer-layout"><article className="answer-card"><p className="eyebrow">Dronzer's answer</p><p className="answer-text">{result.answer || 'No relevant information was found in your documents.'}</p></article><aside className="sources-card"><div className="panel-heading"><h2>Sources</h2><span className="count">{result.sources.length}</span></div>{result.sources.length ? result.sources.map((source, index) => <div className="source" key={`${source.documentId}-${source.chunkIndex}-${index}`}><span className="source-index">0{index + 1}</span><div><strong>{source.filename}</strong><small>Chunk {source.chunkIndex} · {source.similarity ? `${Math.round(source.similarity * 100)}% match` : 'Similarity unavailable'}</small></div></div>) : <p className="muted">No source passages matched this question.</p>}</aside></section>}</>;
}

function NotesView({ notes, onChange }: { notes: NoteRecord[]; onChange: (notes: NoteRecord[]) => void }) {
  const [title, setTitle] = useState(''); const [editing, setEditing] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function save() { if (!title.trim()) return; setBusy(true); setError(''); try { if (editing === null) { const note = await api.createNote(title.trim()); onChange([note, ...notes]); } else { const note = await api.updateNote(editing, title.trim()); onChange(notes.map(item => item.id === note.id ? note : item)); } setTitle(''); setEditing(null); } catch (requestError) { setError(readableError(requestError, 'Could not save that note.')); } finally { setBusy(false); } }
  async function remove(id: number) { setError(''); try { await api.deleteNote(id); onChange(notes.filter(note => note.id !== id)); } catch (requestError) { setError(readableError(requestError, 'Could not delete that note.')); } }
  return <><SectionHeader eyebrow="Your thinking space" title="Notes" description="Keep a lightweight trail of ideas alongside your source material." /><section className="note-composer"><label htmlFor="note-title">{editing === null ? 'Capture a note' : 'Edit note'}<input id="note-title" value={title} onChange={event => setTitle(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') save(); }} placeholder="A thought worth keeping..." /></label><button className="button button-dark" onClick={save} disabled={busy || !title.trim()}>{busy ? 'Saving...' : editing === null ? 'Add note' : 'Save note'}</button></section>{error && <StatusMessage>{error}</StatusMessage>}<section className="notes-list">{notes.length ? notes.map(note => <article className="note-card" key={note.id}><span className="note-dot" /><p>{note.title}</p><div className="note-actions"><button className="text-button" onClick={() => { setEditing(note.id); setTitle(note.title); }}>Edit</button><button className="text-button danger-text" onClick={() => remove(note.id)}>Delete</button></div></article>) : <div className="panel"><EmptyState title="No notes yet" text="Capture a decision, idea, or question above." /></div>}</section></>;
}

function DocumentRow({ document }: { document: DocumentRecord }) { return <div className="document-row"><span className="file-badge">{document.filename.toLowerCase().endsWith('.pdf') ? 'PDF' : 'TXT'}</span><div><strong>{document.filename}</strong><small>Indexed {formatDate(document.uploadedAt)}</small></div><span className="row-status">Ready</span></div>; }
function EmptyState({ title, text, action, onClick }: { title: string; text: string; action?: string; onClick?: () => void }) { return <div className="empty-state"><strong>{title}</strong><p>{text}</p>{action && <button className="text-button" onClick={onClick}>{action} →</button>}</div>; }
