CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255),
    content TEXT,
    uploaded_at TIMESTAMP(6),
    user_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_text TEXT,
    chunk_index INTEGER,
    document_id BIGINT REFERENCES documents(id)
);

CREATE TABLE IF NOT EXISTS document_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id BIGINT UNIQUE REFERENCES document_chunks(id),
    embedding vector(768)
);

CREATE TABLE IF NOT EXISTS notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255)
);

DELETE FROM document_embeddings;

ALTER TABLE document_embeddings
    ALTER COLUMN embedding TYPE vector(768)
    USING embedding::vector(768);

CREATE INDEX IF NOT EXISTS document_chunks_document_id_idx
    ON document_chunks(document_id);

CREATE INDEX IF NOT EXISTS documents_user_id_idx
    ON documents(user_id);

CREATE INDEX IF NOT EXISTS document_embeddings_embedding_hnsw_idx
    ON document_embeddings USING hnsw (embedding vector_cosine_ops);
